/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.GameController;
import Controller.UIController;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author pagli
 */
public class GameOver extends javax.swing.JPanel {

    /**
     * Creates new form GameOver
     */
    public GameOver() {
        initComponents();

        this.setBackground(new Color(180,201,202));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        playAgainButton = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();

        setBackground(new Color(180, 201, 202));

        startButton.setBackground(new Color(0, 0, 0));
        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuIcons/icons8-menu-60.png"))); // NOI18N
        startButton.setBorderPainted(false);
        startButton.setOpaque(false);
        startButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                UIController.backFromGameOver();
            }
        });

        playAgainButton.setBackground(new Color(0, 0, 0));
        playAgainButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuIcons/icons8-play-60.png"))); // NOI18N
        playAgainButton.setBorderPainted(false);
        playAgainButton.setOpaque(false);
        playAgainButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                UIController.playAgain();
            }
        });

        scoreLabel.setFont(new Font("Comic Sans MS", 1, 24)); // NOI18N
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("Your score : " + GameController.getPlayer().score);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Backgrounds/gameover.png"))); // NOI18N
        logoLabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoLabel)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playAgainButton)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(logoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(scoreLabel)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playAgainButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
