/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.UIController;
import Utils.FileUtils;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author pagli
 */
public class Scores extends javax.swing.JPanel {

    /**
     * Creates new form Scores
     */
    public Scores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        username1 = new javax.swing.JLabel();
        point1 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        point2 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        point3 = new javax.swing.JLabel();
        username4 = new javax.swing.JLabel();
        point4 = new javax.swing.JLabel();
        username5 = new javax.swing.JLabel();
        point5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(180, 201, 202));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuIcons/icons8-back-arrow-50.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setOpaque(false);
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                UIController.backFromScores();
            }
        });

        username1.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        username1.setText(FileUtils.readSequences("Resources/punteggi.csv")[0][0]);

        point1.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        point1.setText(FileUtils.readSequences("Resources/punteggi.csv")[0][1]);

        username2.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        username2.setText(FileUtils.readSequences("Resources/punteggi.csv")[1][0]);

        point2.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        point2.setText(FileUtils.readSequences("Resources/punteggi.csv")[1][1]);

        username3.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        username3.setText(FileUtils.readSequences("Resources/punteggi.csv")[2][0]);

        point3.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        point3.setText(FileUtils.readSequences("Resources/punteggi.csv")[2][1]);

        username4.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        username4.setText(FileUtils.readSequences("Resources/punteggi.csv")[3][0]);

        point4.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        point4.setText(FileUtils.readSequences("Resources/punteggi.csv")[3][1]);

        username5.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        username5.setText(FileUtils.readSequences("Resources/punteggi.csv")[4][0]);

        point5.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        point5.setText(FileUtils.readSequences("Resources/punteggi.csv")[4][1]);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(username1)
                        .addComponent(username2)
                        .addComponent(username3))
                    .addComponent(username4))
                .addGap(199, 199, 199)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(point5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(point3)
                                .addComponent(point2)
                                .addComponent(point1))
                            .addComponent(point4))
                        .addGap(12, 12, 12)))
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username1)
                    .addComponent(point1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(point2)
                    .addComponent(username2))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username3)
                    .addComponent(point3))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username4)
                    .addComponent(point4))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username5)
                    .addComponent(point5))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        username1.getAccessibleContext().setAccessibleName("username1");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel point1;
    private javax.swing.JLabel point2;
    private javax.swing.JLabel point3;
    private javax.swing.JLabel point4;
    private javax.swing.JLabel point5;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username4;
    private javax.swing.JLabel username5;
    // End of variables declaration//GEN-END:variables

    public static int max() {
        int max = Integer.parseInt(FileUtils.readSequences("Resources/punteggi.csv")[0][1]);
        for (int i = 0; i < 5; i++) {
            if (Integer.parseInt(FileUtils.readSequences("Resources/punteggi.csv")[i][1]) > max)
                max = Integer.parseInt(FileUtils.readSequences("Resources/punteggi.csv")[i][1]);
        }
        return max;
    }
}
