/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.UIController;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author pagli
 */
public class Skins extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Skins() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLabel = new javax.swing.JLabel();
        skinButton1 = new javax.swing.JButton();
        skinButton2 = new javax.swing.JButton();
        skinButton3 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(180, 201, 202));

        textLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        textLabel.setText("Chose Your Helicopter");

        skinButton1.setBackground(new java.awt.Color(0, 0, 0));
        skinButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Skin/skin1.gif"))); // NOI18N
        skinButton1.setOpaque(false);
        skinButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                skin1();
            }
        });

        skinButton2.setBackground(new java.awt.Color(0, 0, 0));
        skinButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Skin/skin2.gif"))); // NOI18N
        skinButton2.setOpaque(false);
        skinButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                skin2();
            }
        });

        skinButton3.setBackground(new java.awt.Color(0, 0, 0));
        skinButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Skin/skin3.gif"))); // NOI18N
        skinButton3.setOpaque(false);
        skinButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                skin3();
            }
        });

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuIcons/icons8-back-arrow-50.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setOpaque(false);
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                UIController.backFromSkins();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(skinButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(skinButton2)
                        .addGap(46, 46, 46)
                        .addComponent(skinButton3)
                        .addGap(54, 54, 54))))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(textLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(textLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(skinButton1)
                    .addComponent(skinButton2)
                    .addComponent(skinButton3))
                .addGap(150, 150, 150))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton skinButton1;
    private javax.swing.JButton skinButton2;
    private javax.swing.JButton skinButton3;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel textLabel;
    public String skinPath = "/Resources/Skin/skin1.gif";
    public String recoverySkinPath = "/Resources/Skin/skin1.gif";
    // End of variables declaration//GEN-END:variables

    public void skin1() {
        this.skinPath = "/Resources/Skin/skin1.gif";
        this.recoverySkinPath = "/Resources/Skin/skin1.gif";
    }

    public void skin2() {
        this.skinPath = "/Resources/Skin/skin2.gif";
        this.recoverySkinPath = "/Resources/Skin/skin2.gif";
    }

    public void skin3() {
        this.skinPath = "/Resources/Skin/skin3.gif";
        this.recoverySkinPath = "/Resources/Skin/skin3.gif";
    }

}
