/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.UIController;

/**
 *
 * @author pagli
 */
public class Start extends javax.swing.JPanel {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        scoresButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        skinsButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(180, 201, 202));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Backgrounds/jHelicoperLogo.png"))); // NOI18N

        usernameTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        usernameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTextField.setText("Username");

        scoresButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuIcons/icons8-cup-60.png"))); // NOI18N
        scoresButton.setBorderPainted(false);
        scoresButton.setContentAreaFilled(false);
        scoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoresButtonActionPerformed(evt);
            }
        });


        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuIcons/icons8-play-60.png"))); // NOI18N
        playButton.setBorderPainted(false);
        playButton.setContentAreaFilled(false);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        skinsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuIcons/icons8-helicopter-60.png"))); // NOI18N
        skinsButton.setBorderPainted(false);
        skinsButton.setContentAreaFilled(false);
        skinsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skinsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(skinsButton)
                .addGap(214, 214, 214)
                .addComponent(scoresButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playButton)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoLabel)
                .addGap(45, 45, 45)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(skinsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scoresButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void scoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoresButtonActionPerformed
        UIController.scores();
    }//GEN-LAST:event_scoresButtonActionPerformed

    private void skinsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameLabelActionPerformed
        UIController.skins();
    }//GEN-LAST:event_usernameLabelActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        UIController.helicopter();
    }//GEN-LAST:event_playButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton playButton;
    private javax.swing.JButton scoresButton;
    private javax.swing.JButton skinsButton;
    public javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
